/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMeSessionsRouteImport } from './routes/_authenticated.me.sessions'
import { Route as AuthenticatedMeSecurityRouteImport } from './routes/_authenticated.me.security'
import { Route as AuthenticatedMeAccessRouteImport } from './routes/_authenticated.me.access'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated.admin.services'
import { Route as AuthenticatedAdminScopesRouteImport } from './routes/_authenticated.admin.scopes'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated.admin.roles'
import { Route as AuthenticatedAdminResourceGrantsRouteImport } from './routes/_authenticated.admin.resource-grants'
import { Route as AuthenticatedAdminPoliciesRouteImport } from './routes/_authenticated.admin.policies'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated.admin.permissions'
import { Route as AuthenticatedAdminGroupsRouteImport } from './routes/_authenticated.admin.groups'
import { Route as AuthenticatedAdminExplainRouteImport } from './routes/_authenticated.admin.explain'
import { Route as AuthenticatedAdminDenyRulesRouteImport } from './routes/_authenticated.admin.deny-rules'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated.admin.audit'
import { Route as AuthenticatedAdminAssignmentsRouteImport } from './routes/_authenticated.admin.assignments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeSessionsRoute = AuthenticatedMeSessionsRouteImport.update({
  id: '/me/sessions',
  path: '/me/sessions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeSecurityRoute = AuthenticatedMeSecurityRouteImport.update({
  id: '/me/security',
  path: '/me/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeAccessRoute = AuthenticatedMeAccessRouteImport.update({
  id: '/me/access',
  path: '/me/access',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminScopesRoute =
  AuthenticatedAdminScopesRouteImport.update({
    id: '/admin/scopes',
    path: '/admin/scopes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminResourceGrantsRoute =
  AuthenticatedAdminResourceGrantsRouteImport.update({
    id: '/admin/resource-grants',
    path: '/admin/resource-grants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPoliciesRoute =
  AuthenticatedAdminPoliciesRouteImport.update({
    id: '/admin/policies',
    path: '/admin/policies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGroupsRoute =
  AuthenticatedAdminGroupsRouteImport.update({
    id: '/admin/groups',
    path: '/admin/groups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminExplainRoute =
  AuthenticatedAdminExplainRouteImport.update({
    id: '/admin/explain',
    path: '/admin/explain',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDenyRulesRoute =
  AuthenticatedAdminDenyRulesRouteImport.update({
    id: '/admin/deny-rules',
    path: '/admin/deny-rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAssignmentsRoute =
  AuthenticatedAdminAssignmentsRouteImport.update({
    id: '/admin/assignments',
    path: '/admin/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/deny-rules': typeof AuthenticatedAdminDenyRulesRoute
  '/admin/explain': typeof AuthenticatedAdminExplainRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/admin/resource-grants': typeof AuthenticatedAdminResourceGrantsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/scopes': typeof AuthenticatedAdminScopesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/me/access': typeof AuthenticatedMeAccessRoute
  '/me/security': typeof AuthenticatedMeSecurityRoute
  '/me/sessions': typeof AuthenticatedMeSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/deny-rules': typeof AuthenticatedAdminDenyRulesRoute
  '/admin/explain': typeof AuthenticatedAdminExplainRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/admin/resource-grants': typeof AuthenticatedAdminResourceGrantsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/scopes': typeof AuthenticatedAdminScopesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/me/access': typeof AuthenticatedMeAccessRoute
  '/me/security': typeof AuthenticatedMeSecurityRoute
  '/me/sessions': typeof AuthenticatedMeSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/deny-rules': typeof AuthenticatedAdminDenyRulesRoute
  '/_authenticated/admin/explain': typeof AuthenticatedAdminExplainRoute
  '/_authenticated/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/_authenticated/admin/resource-grants': typeof AuthenticatedAdminResourceGrantsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/scopes': typeof AuthenticatedAdminScopesRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/me/access': typeof AuthenticatedMeAccessRoute
  '/_authenticated/me/security': typeof AuthenticatedMeSecurityRoute
  '/_authenticated/me/sessions': typeof AuthenticatedMeSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/assignments'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/deny-rules'
    | '/admin/explain'
    | '/admin/groups'
    | '/admin/permissions'
    | '/admin/policies'
    | '/admin/resource-grants'
    | '/admin/roles'
    | '/admin/scopes'
    | '/admin/services'
    | '/me/access'
    | '/me/security'
    | '/me/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/assignments'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/deny-rules'
    | '/admin/explain'
    | '/admin/groups'
    | '/admin/permissions'
    | '/admin/policies'
    | '/admin/resource-grants'
    | '/admin/roles'
    | '/admin/scopes'
    | '/admin/services'
    | '/me/access'
    | '/me/security'
    | '/me/sessions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin/assignments'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/deny-rules'
    | '/_authenticated/admin/explain'
    | '/_authenticated/admin/groups'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/policies'
    | '/_authenticated/admin/resource-grants'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/scopes'
    | '/_authenticated/admin/services'
    | '/_authenticated/me/access'
    | '/_authenticated/me/security'
    | '/_authenticated/me/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me/sessions': {
      id: '/_authenticated/me/sessions'
      path: '/me/sessions'
      fullPath: '/me/sessions'
      preLoaderRoute: typeof AuthenticatedMeSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/security': {
      id: '/_authenticated/me/security'
      path: '/me/security'
      fullPath: '/me/security'
      preLoaderRoute: typeof AuthenticatedMeSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/access': {
      id: '/_authenticated/me/access'
      path: '/me/access'
      fullPath: '/me/access'
      preLoaderRoute: typeof AuthenticatedMeAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/scopes': {
      id: '/_authenticated/admin/scopes'
      path: '/admin/scopes'
      fullPath: '/admin/scopes'
      preLoaderRoute: typeof AuthenticatedAdminScopesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/resource-grants': {
      id: '/_authenticated/admin/resource-grants'
      path: '/admin/resource-grants'
      fullPath: '/admin/resource-grants'
      preLoaderRoute: typeof AuthenticatedAdminResourceGrantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/policies': {
      id: '/_authenticated/admin/policies'
      path: '/admin/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AuthenticatedAdminPoliciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/groups': {
      id: '/_authenticated/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/explain': {
      id: '/_authenticated/admin/explain'
      path: '/admin/explain'
      fullPath: '/admin/explain'
      preLoaderRoute: typeof AuthenticatedAdminExplainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/deny-rules': {
      id: '/_authenticated/admin/deny-rules'
      path: '/admin/deny-rules'
      fullPath: '/admin/deny-rules'
      preLoaderRoute: typeof AuthenticatedAdminDenyRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/assignments': {
      id: '/_authenticated/admin/assignments'
      path: '/admin/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AuthenticatedAdminAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAssignmentsRoute: typeof AuthenticatedAdminAssignmentsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDenyRulesRoute: typeof AuthenticatedAdminDenyRulesRoute
  AuthenticatedAdminExplainRoute: typeof AuthenticatedAdminExplainRoute
  AuthenticatedAdminGroupsRoute: typeof AuthenticatedAdminGroupsRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminPoliciesRoute: typeof AuthenticatedAdminPoliciesRoute
  AuthenticatedAdminResourceGrantsRoute: typeof AuthenticatedAdminResourceGrantsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminScopesRoute: typeof AuthenticatedAdminScopesRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedMeAccessRoute: typeof AuthenticatedMeAccessRoute
  AuthenticatedMeSecurityRoute: typeof AuthenticatedMeSecurityRoute
  AuthenticatedMeSessionsRoute: typeof AuthenticatedMeSessionsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAssignmentsRoute: AuthenticatedAdminAssignmentsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDenyRulesRoute: AuthenticatedAdminDenyRulesRoute,
  AuthenticatedAdminExplainRoute: AuthenticatedAdminExplainRoute,
  AuthenticatedAdminGroupsRoute: AuthenticatedAdminGroupsRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminPoliciesRoute: AuthenticatedAdminPoliciesRoute,
  AuthenticatedAdminResourceGrantsRoute: AuthenticatedAdminResourceGrantsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminScopesRoute: AuthenticatedAdminScopesRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedMeAccessRoute: AuthenticatedMeAccessRoute,
  AuthenticatedMeSecurityRoute: AuthenticatedMeSecurityRoute,
  AuthenticatedMeSessionsRoute: AuthenticatedMeSessionsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
